# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "BiznagaFest 2021"
email: "gdgmalaga@gmail.com"
description: "BiznagaFest is a set of events all around the world"
baseurl: "/"
url: "https://gdg-x.github.io"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-43643469-5"
googleAnalyticsSiteUrl: "gdg-x.github.io"
siteVerification: "b9imDOrFawXaBXCC4r3uJDdswSYcalD-wWpMYhFq-no"

# Organizer Info
organizerName: "GDG Málaga"
organizerAlternateName: "Google Developer Group Málaga"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "gdgmalaga@gmail.com"
organizerLogo: "/img/logos/logo-color.png"
organizerLink: "https://gdgmalaga.dev/"

# Head
metaKeywords: "event, gdg, devfest, google, programming, android, chrome, developers, lviv"
twitterAccount: "@GDGMalaga"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "https://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "Home"}
 #- {permalink: "/blog/", text: "Blog"}
 #- {permalink: "/schedule/", text: "Schedule"}
 #- {permalink: "/speakers/", text: "Speakers"}
 - {permalink: "/team/", text: "Team"}
 - {permalink: "/logistics/", text: "Logistics"}
 - {permalink: "/cod/", text: "Code of Conduct"}
 #- {permalink: "/hackathon/", text: "Hackathon"}
bottomNavigationLinks:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
rightNavigationButtons:
# - {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}

# Hero Block
heroImage: "home.jpg"
heroTitle: "BiznagaFest <typeout> 2021"
eventDate: "15/01/2022"
typeoutTextValues: '"", "Season", "Málaga"'
typeoutFallback: "Season"
heroButtons:
 - {link: "https://ocm.gdgmalaga.dev/", text: "Become a speaker"}
 - {permalink: "https://www.eventbrite.es/e/biznagafest-tickets-189228326017", text: "Buy tickets"}

# About Block
aboutTitle: "About BiznagaFest"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Networking", image: "hackathon.jpg", text: "Enjoy meeting and connecting with the amazing people that are part of the Málaga tech community!" }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "400", specialCharacter: "+", info: "attendees", detail: "from everywhere"}
 - {count: "10", specialCharacter: "+", info: "hours", detail: "of talks and hand in sessions"}
 - {count: "25", specialCharacter: "+", info: "speakers", detail: "from Spain and beyond"}
 - {count: "5", specialCharacter: "", info: "parallel tracks", detail: "plus networking"}

# Latest News Block
latestNewsTitle: "Latest news"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Speakers - Coming Soon"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Coming Soon"
eventLocationLink: "http://cabinet.kinopalace.lviv.ua/showtimes/"
eventStreetAddress: "Málaga"
eventAddressLocality: "Spain"
eventAddressLocalityRegion: "Málaga"
eventPostalCode: ""
eventAddressCountry: "Spain"
eventStartTime: "2021-10-25T10:00"
eventDoorTime: "09:00"
eventEndTime: "2021-10-25T20:00"
eventPlaceCoordinates: "36.7647499, -4.5642737"
mapCenterCoordinates: "36.7647499, -4.5642737"
mapMobileCenterCoordinates: "36.7647499, -4.5642737"

# Venue Block
venueBlockTitle: "The Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_2.jpg"
venueSmallImage2: "venue_4.jpg"
venueTitle: "E.T.S. De Ingeniería Informática"
venueFeatures: ["Amazing transport connections", "Located in the heart of the University of Málaga Campus"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "BiznagaFest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "10"
  priceCurrency: "EUR"
  ticketsNumber: "150"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: [Full access to the conference"]
  validFrom: "2021-08-25T10:00"
  validThrough: "2021-09-30T23:59"
  soldOut: true
  soldOutText: "Coming Soon"
 -
  name: "General"
  price: "15"
  priceCurrency: "EUR"
  ticketsNumber: "100"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: [Full access to the conference"]
  validFrom: "2021-10-01T00:00"
  validThrough: "2021-10-23T23:59"
  #disabled: true
  soldOut: true
  soldOutText: "Coming Soon"
 -
  name: "Student"
  price: "5"
  priceCurrency: "EUR"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: [Full access to the conference"]
  validFrom: "2021-08-20T10:00"
  validThrough: "2021-10-23T23:59"
  soldOut: true
  soldOutText: "Coming Soon"

# Footer
socialLinks:
 - {link: "https://twitter.com/intent/user?screen_name=GDGMalaga", icon: "twitter"}
footerBlocks:
 -
  title: "Links"
  links:
   - {link: "https://www.meetup.com/es-ES/Google-Developer-Group-Malaga/", text: "GDG Málaga"}
   - {link: "https://developers.google.com", text: "Google Developers"}
   - {link: "https://devfest19.gdgmalaga.dev/", text: "DevFest Malaga '19"}
   - {link: "https://devfest18.gdgmalaga.dev/", text: "DevFest Malaga '18"}
   - {link: "https://devfest17.gdgmalaga.dev/", text: "DevFest Malaga '17"}
 -
  title: "Contacts"
  links:
   - {link: "mailto:gdgmalaga@gmail.com", text: "gdgmalaga@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: false

# Team Block
teamBlockTitle: "About us"
aboutUs: "Google is known all around the world. Everyone is 'googling', checking on 'maps' and communicating in 'gmail'. For simple users, they are services that just works, but not for us. Developers see much more: APIs, scalability issues, complex technology stacks. And that is what GDG is about.

Google Developers Group (GDG) Málaga is open and volunteer geek community who create exciting projects and share experience about technologies with a passion.

Our goal is to organize space to connect the best industry experts with Málaga audience to boost development of IT. "

# Logistics Find Way Block
findWayTitle: "Find your way here"
findWayDistance: "Distance"
findWayDriving: "DRIVING"
findWayWalking: "WALKING"
findWayBicycling: "BICYCLING"
findWayTransit: "TRANSIT"
findWayFindFlight: "Find Flight"
logisticsMapCenterCoordinates: "36.7647499, -4.5642737"
logisticsMapMobileCenterCoordinates: "36.7647499, -4.5642737"
logisticsMapAutoDirections: false

# Logistics Direction Details Block
directionDetailsImage: "direction.jpg"
directionDetailsTitle: "Get around Málaga"
directionDetailsCards:
 - {title: "From the Airport", information: 'Airport is right at the city border. It is easily reachable by car, public transport or taxi. More information is available at <a href="https://www.aeropuertodemalaga-costadelsol.com/">airport website</a>.'}
 - {title: "Public Transit", information: 'Google Transit is available in Málaga. So you can find your way in Google Maps. Moreover, you can download any of the offline public transit apps available for Málaga.'}
 - {title: "Hotels", information: 'Málaga is well known for its turism, and has lots of great hotels and hostels. Have a look online in your favorite travel website and choose any of the enchanting places you can find around!'}
#directionDetailsWideCards:
# -
#  title: "Questions?"
#  subCards:
#   -
#    title: "Hotels"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Registration"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}
#   -
#    title: "Attendance Details"
#    links:
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "InterContinental"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "The Hotel Rex"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Westin Market Street"}
#     - {link: "https://plus.google.com/b/102444623953913144164", text: "Hotel Adagio"}

# Hackathon
hackathonTitle: "Hackathon"
enableHackathon: true

# Hackathon About Block
aboutHackathonTitle: "Meet our themes"
hackathonRows:
 - {title: "Android Wear", image: "hackathon-0.png", details: "The front doors will be locked because this is after hours, please park behind the building and come to the door nearest the parking lot.<br><br>Our last meeting showed that there was a lot of interest in Android Wear so we decided to put on an Android Wear Hackathon to see what you could come up with! We realize that this is pretty short notice so we hope you can help us spread the word! There will be pizza, prizes and a great group of geeks to spend the evening coding with! Even if you don't have an app idea come on in and lend a hand to someone else or maybe find inspiration once you're here!"}
 - {title: "Google Glass", image: "hackathon-1.png", details: "We love wearable computing especially Google Glass for which we want to gather the break up community in order to boost innovation.<br><br>Coding an app on Google Glass needs its Rockstar Dev : the team needs a fast learner with solid skills on Android. He knows his way around Android SDK, already checked the Glass Developement Kit (GDK) quick start guide allowing him to jump start developing an app for Glass.The Designer has the hard task to build the visual identity from the ground up, he has strong UX knowledge and a deep understanding of the new rules set by the Glass. His design skills give him the credibility to decide the most effective UI and the most compelling Glass experience."}
 - {title: "Polymer", image: "hackathon-2.png", details: "Polymer is a library that introduces web components. Web components are small elements on a page that can be extended and incorporated in web applications. The result is an increase in productivity.<br><br>We used Polymer mainly to explore the concept of web components. The transition of Google to material design was also a factor.While the library was never touched by the team, it still was painless to wireframe the application. Later on we incorporated some Polymer components in the design. We didn’t use the full potential of Polymer because of the limited time."}

# Hackathon Judges Block
judgesImage: "judges.jpg"
judgesTitle: "Judges"

# Hackathon Prizes Block
prizesTitle: "Prizes"
prizes:
 - {title: "2nd Place", image: "prize-2.png", info: "Amazing Moto 360"}
 - {title: "1nd Place", image: "prize-1.png", info: "Nexus 5 with pre-installed Android L"}
 - {title: "3nd Place", image: "prize-3.png", info: "Useful Chromecast"}

# Hackathon Location Block
hackathonLocationBlockTitle: "Location"
hackathonLocationName: "Communa"
hackathonLocationLink: "http://communa.net.ua/"
hackathonStreetAddress: "1 Halytska St"
hackathonAddressLocality: "Lviv"
hackathonAddressLocalityRegion: "Lvivska"
hackathonPostalCode: "79000"
hackathonAddressCountry: "Ukraine"
hackathonTimeTitle: "Hack through"
hackathonStartTime: "2021-10-24T10:00"
hackathonDoorTime: "09:00"
hackathonEndTime: "2021-10-25T00:00"
viewOnMap: "View on Google Maps"
hackathonPlaceCoordinates: "49.840999, 24.031144"
hackathonMapCenterCoordinates: "49.840696, 24.028754"
hackathonMapMobileCenterCoordinates: "49.841639, 24.031182"
